namespace DbTool.DbProvider.MySql
{
    internal enum MySqlDbType
    {
        BigInt,
        Binary,
        Bit,
        Char,
        Date,
        DateTime,
        DateTime2,
        DateTimeOffset,
        Decimal,
        Float,
        Image,
        Int,
        Money,
        NChar,
        NText,
        Numeric,
        NVarChar,
        Real,
        RowVersion,
        SmallDateTime,
        SmallInt,
        SmallMoney,
        Text,
        LongText,
        Time,
        Timestamp,
        TinyInt,
        UniqueIdentifier,
        VarBinary,
        VarChar,
        Variant,
        Xml,
        Structured
    }
}
